/**
 * Charts: how a model surface is drawn, as regions, ports and bands (port note 20).
 *
 * - Each vertex w of G₀ has a convex **region** in the chart (a polygon's interior, a disk around a base point).
 * - Each oriented edge x of G₀ has a **port** on the boundary of the region of its source: a segment through which
 *   the strands along x leave. Its lateral coordinate u runs from −1 (right) to +1 (left), looking outwards along x.
 * - Each edge of G₀ is either **glued** (the port of x is identified with the port of x̄, u ↦ −u, as for polygon sides,
 *   possibly after a straight stub sticking out of the region) or a drawn **band** (a petal around a point of the
 *   plane), along which the strands run side by side.
 *
 * Hyperbolic charts use Klein coordinates (straight lines are geodesics); the others are Euclidean.
 *
 * @module
 */
import type { Edge, OrientedEdge, Vertex } from "../graph/ribbon-graph";
import { Complex } from "../math/complex";
import type { Color } from "../math/color";
import { type DiskIsometry, regularPolygon, sidePairing } from "../geometry/hyperbolic";
import {
  spineOf,
  type PlaneModel,
  type PolygonModel,
  type Spine,
  type SpineNames,
  type SurfaceModel,
} from "../examples/models";

export interface Port {
  /** The ends of the port: lateral coordinate −1 and +1 (right and left, looking outwards). */
  readonly right: Complex;
  readonly left: Complex;
  /** The outward unit normal. */
  readonly outward: Complex;
  /** The length of a straight stub outside the region before the gluing (0 for polygon sides). */
  readonly stub: number;
}

export interface Region {
  /** A convex polygon, counterclockwise. */
  readonly boundary: readonly Complex[];
  readonly center: Complex;
}

export type Band =
  | { readonly kind: "glue" }
  /** The centreline from the port of the forward orientation to the port of the backward one, and its half width. */
  | { readonly kind: "path"; readonly centerline: readonly Complex[]; readonly halfWidth: number };

/** Things to draw that belong to the model, not to G. */
export type Decoration =
  | { readonly kind: "polygon"; readonly vertices: readonly Complex[]; readonly ideal: boolean }
  | {
      readonly kind: "side";
      readonly from: Complex;
      readonly to: Complex;
      readonly label: string;
      readonly color: Color;
    }
  | { readonly kind: "puncture"; readonly at: Complex }
  | { readonly kind: "disk"; readonly center: Complex; readonly radius: number }
  /** A junction of a ribbon model: a convex region (a rounded polygon). */
  | { readonly kind: "region"; readonly boundary: readonly Complex[] }
  | {
      readonly kind: "band";
      readonly centerline: readonly Complex[];
      readonly halfWidth: number;
      readonly color: Color;
    }
  | {
      readonly kind: "stub";
      readonly from: Complex;
      readonly to: Complex;
      readonly halfWidth: number;
      readonly label: string;
      readonly color: Color;
    };

/** The deck transformations generated by the gluings: an isometry (hyperbolic) or a translation (flat) per port. */
export type Deck =
  | { readonly kind: "hyperbolic"; readonly generators: ReadonlyMap<OrientedEdge, DiskIsometry> }
  | { readonly kind: "translation"; readonly generators: ReadonlyMap<OrientedEdge, Complex> };

export interface Chart {
  readonly geometry: "hyperbolic" | "euclidean";
  readonly spine: Spine;
  readonly regions: ReadonlyMap<Vertex, Region>;
  readonly ports: ReadonlyMap<OrientedEdge, Port>;
  readonly bands: ReadonlyMap<Edge, Band>;
  readonly decorations: readonly Decoration[];
  /** For polygons: the generators of the deck group, one per side (the copy across that side). */
  readonly deck?: Deck;
}

/** The chart of a model. The spine is built with the given names (it must be the G₀ of the fibred surface drawn). */
export function chartOf(
  model: SurfaceModel,
  naming: SpineNames = {},
  spine: Spine = spineOf(model, naming),
): Chart {
  switch (model.kind) {
    case "polygon":
      return polygonChart(model, spine);
    case "plane":
      return planeChart(model, spine);
    case "ribbon":
      return ribbonChart(spine);
  }
}

// ─── Polygons ───────────────────────────────────────────────────────────────────────────────

/** How much of each side carries strands (the rest is near the vertices, which are cusps for ideal polygons). */
const SIDE_FRACTION = { ideal: 0.5, compact: 0.75, flat: 0.8 };

function polygonChart(model: PolygonModel, spine: Spine): Chart {
  const n = model.word.length;
  const hyperbolic = model.geometry.kind !== "flat";
  const vertices =
    model.geometry.kind === "flat"
      ? normalize(model.geometry.vertices.map(([x, y]) => new Complex(x, y)))
      : regularPolygon(n, model.geometry.kind);
  const center = hyperbolic ? Complex.ZERO : centroid(vertices);
  const [w0] = spine.graph.vertices as [Vertex];
  const sides = spine.sides as readonly OrientedEdge[];
  const fraction = SIDE_FRACTION[model.geometry.kind];
  const ports = new Map<OrientedEdge, Port>();
  const decorations: Decoration[] = [{ kind: "polygon", vertices, ideal: model.geometry.kind === "ideal" }];
  sides.forEach((x, k) => {
    const [p, q] = [vertices[k] as Complex, vertices[(k + 1) % n] as Complex];
    const mid = p.add(q).scale(0.5);
    const half = q.sub(p).scale(fraction / 2);
    const tangent = q.sub(p).scale(1 / q.sub(p).abs());
    // Counterclockwise along the side is "left" when looking outwards; the outward normal is the tangent turned right.
    ports.set(x, {
      right: mid.sub(half),
      left: mid.add(half),
      outward: new Complex(tangent.im, -tangent.re),
      stub: 0,
    });
    decorations.push({ kind: "side", from: p, to: q, label: x.name, color: x.color });
  });
  const partner = (k: number) => sides.indexOf((sides[k] as OrientedEdge).reversed);
  const deck: Deck = hyperbolic
    ? {
        kind: "hyperbolic",
        generators: new Map(sides.map((x, k) => [x.reversed, sidePairing(vertices, k, partner(k))] as const)),
      }
    : {
        kind: "translation",
        generators: new Map(
          sides.map((x, k) => {
            const mid = (i: number) =>
              (vertices[i] as Complex).add(vertices[(i + 1) % n] as Complex).scale(0.5);
            return [x.reversed, mid(partner(k)).sub(mid(k))] as const;
          }),
        ),
      };
  return {
    geometry: hyperbolic ? "hyperbolic" : "euclidean",
    spine,
    regions: new Map([[w0, { boundary: vertices, center }]]),
    ports,
    bands: new Map(spine.graph.edges.map((e) => [e, { kind: "glue" }] as const)),
    decorations,
    deck,
  };
}

// ─── The plane ──────────────────────────────────────────────────────────────────────────────

function planeChart(model: PlaneModel, spine: Spine): Chart {
  const points = normalize(
    model.points.map(([x, y]) => new Complex(x, y)),
    0.7,
  );
  const spacing = minimalDistance(points);
  const loopRadius = Math.min(0.3 * spacing, 0.25);
  const ports = new Map<OrientedEdge, Port>();
  const regions = new Map<Vertex, Region>();
  const bands = new Map<Edge, Band>();
  const decorations: Decoration[] = points.map((at) => ({ kind: "puncture", at }));
  const lassos = spine.lassos as readonly OrientedEdge[];
  const bandHalfWidth = loopRadius * 0.45;

  /** A disk region of radius r, with ports at the given angles (counterclockwise order of the star). */
  const disk = (w: Vertex, c: Complex, r: number, angles: Map<OrientedEdge, number>, portWidth: number) => {
    regions.set(w, { boundary: circle(c, r, 32), center: c });
    decorations.push({ kind: "disk", center: c, radius: r });
    for (const [x, angle] of angles) {
      const outward = Complex.fromPolar(1, angle);
      const at = c.add(outward.scale(r));
      const lateral = new Complex(-outward.im, outward.re).scale(portWidth / 2); // left of outward
      ports.set(x, { right: at.sub(lateral), left: at.add(lateral), outward, stub: 0 });
    }
  };
  /** The petal of the lasso x around the point p, leaving through port(x) and returning through port(x̄). */
  const petal = (x: OrientedEdge, p: Complex) => {
    const [out, back] = [ports.get(x) as Port, ports.get(x.reversed) as Port];
    const [start, end] = [out.right.add(out.left).scale(0.5), back.right.add(back.left).scale(0.5)];
    const towardBase = start.add(end).scale(0.5).sub(p).arg();
    const alpha = 0.35;
    const arc = Array.from({ length: 33 }, (_, i) =>
      p.add(Complex.fromPolar(loopRadius, towardBase + alpha + ((2 * Math.PI - 2 * alpha) * i) / 32)),
    );
    const centerline = [
      start,
      start.add(out.outward.scale(loopRadius * 0.3)),
      ...arc,
      end.add(back.outward.scale(loopRadius * 0.3)),
      end,
    ];
    bands.set(x.edge, {
      kind: "path",
      centerline: x.isForward ? centerline : centerline.toReversed(),
      halfWidth: bandHalfWidth,
    });
    decorations.push({ kind: "band", centerline, halfWidth: bandHalfWidth, color: x.color });
  };

  if (model.spine === "rose") {
    const [w] = spine.graph.vertices as [Vertex];
    const base = normalizeLike(model.points, new Complex(...model.basePoint), 0.7);
    const r = Math.min(0.12, 0.3 * Math.min(...points.map((p) => p.sub(base).abs())));
    const angles = new Map<OrientedEdge, number>();
    const delta = Math.min(0.25, Math.PI / (3 * points.length));
    points.forEach((p, i) => {
      const phi = p.sub(base).arg();
      const x = lassos[i] as OrientedEdge;
      angles.set(x, phi - delta);
      angles.set(x.reversed, phi + delta);
    });
    disk(w, base, r, angles, Math.min(2 * r * Math.sin(delta), 2 * bandHalfWidth));
    points.forEach((p, i) => petal(lassos[i] as OrientedEdge, p));
  } else {
    // The comb: a base point above each point, joined from left to right.
    const height = Math.min(0.35 * spacing + loopRadius, 0.5);
    const r = Math.min(0.08, 0.2 * spacing);
    const bases = points.map((p) => p.add(new Complex(0, height)));
    const vertexOf = (x: OrientedEdge) => x.source;
    points.forEach((_, i) => {
      const x = lassos[i] as OrientedEdge;
      const angles = new Map<OrientedEdge, number>([
        [x, -Math.PI / 2 - 0.35],
        [x.reversed, -Math.PI / 2 + 0.35],
      ]);
      for (const y of spine.graph.star(vertexOf(x)))
        if (y.edge !== x.edge) angles.set(y, spine.graph.star(vertexOf(x)).indexOf(y) === 0 ? Math.PI : 0);
      disk(vertexOf(x), bases[i] as Complex, r, angles, r * 0.9);
    });
    points.forEach((p, i) => petal(lassos[i] as OrientedEdge, p));
    for (const e of spine.graph.edges) {
      if (bands.has(e)) continue;
      const [from, to] = [ports.get(e.forward) as Port, ports.get(e.backward) as Port];
      const centerline = [from.right.add(from.left).scale(0.5), to.right.add(to.left).scale(0.5)];
      bands.set(e, { kind: "path", centerline, halfWidth: r * 0.45 });
      decorations.push({ kind: "band", centerline, halfWidth: r * 0.45, color: e.color });
    }
  }
  return { geometry: "euclidean", spine, regions, ports, bands, decorations };
}

// ─── Ribbon graphs ──────────────────────────────────────────────────────────────────────────

/**
 * A ribbon graph drawn as its fibred surface: a disk per vertex, and a band per edge. The edges of a spanning tree are
 * drawn as real bands; each child disk sits in the direction of its parent's port, with its star rotated so that the
 * band leaves it straight back towards the parent (a tree can be drawn this way with any cyclic orders). The other
 * edges are half-bands glued at their labelled ends (your rectangles, glued in the middle), except loops whose two ends
 * are neighbours in the cyclic order: those are drawn as petals (e.g. a peripheral circle).
 *
 * A vertex of valence k is a rounded k-gon: its ports are chords of its circle (nearly the sides of the inscribed
 * regular k-gon, at most 1.5 radii long), joined by arcs of the circle; the bands are as wide as the ports, so nearly as
 * wide as the junctions.
 */
function ribbonChart(spine: Spine): Chart {
  const graph = spine.graph;
  const vertices = graph.vertices;
  const root = vertices.reduce(
    (best, v) => (graph.valence(v) > graph.valence(best) ? v : best),
    vertices[0] as Vertex,
  );

  // A breadth-first spanning tree, with the angle of every port and the position of every disk (in units of the radius).
  const angle = new Map<OrientedEdge, number>();
  const center = new Map<Vertex, Complex>([[root, Complex.ZERO]]);
  const treeEdges = new Set<Edge>();
  // Loops whose ends are neighbours in the star, with the end that comes first counterclockwise.
  const petals = new Map<Edge, OrientedEdge>();
  for (const e of graph.edges)
    if (e.isLoop && graph.star(e.source).length > 2) {
      if (graph.next(e.forward) === e.backward) petals.set(e, e.forward);
      else if (graph.next(e.backward) === e.forward) petals.set(e, e.backward);
    }
  const setAngles = (first: OrientedEdge, firstAngle: number) => {
    const star = graph.starFrom(first);
    star.forEach((x, k) => angle.set(x, firstAngle + (2 * Math.PI * k) / star.length));
  };
  setAngles(graph.star(root)[0] as OrientedEdge, Math.PI / 2);
  const BAND = 3.2; // distance between the centres of neighbouring disks, in radii
  for (let queue = [root]; queue.length > 0;) {
    const u = queue.shift() as Vertex;
    for (const x of graph.star(u)) {
      const v = x.target;
      if (center.has(v)) continue;
      treeEdges.add(x.edge);
      const theta = angle.get(x) as number;
      center.set(v, (center.get(u) as Complex).add(Complex.fromPolar(BAND, theta)));
      setAngles(x.reversed, theta + Math.PI);
      queue.push(v);
    }
  }

  // Scale everything into the unit disk.
  const stubLength = 0.9;
  const extent = Math.max(...[...center.values()].map((c) => c.abs() + 1 + stubLength), 1);
  const r = 0.9 / extent;
  const shift = [...center.values()].reduce((sum, c) => sum.add(c), Complex.ZERO).scale(-1 / center.size);
  const position = (v: Vertex) => (center.get(v) as Complex).add(shift).scale(r);

  const regions = new Map<Vertex, Region>();
  const ports = new Map<OrientedEdge, Port>();
  const bands = new Map<Edge, Band>();
  const decorations: Decoration[] = [];
  for (const w of vertices) {
    const c = position(w);
    const star = graph.star(w);
    // Half the length of each port: nearly half a side of the inscribed regular k-gon.
    const half = Math.min(r * Math.sin(Math.PI / Math.max(star.length, 2)) * 0.92, 0.75 * r);
    const width = 2 * half;
    const depth = Math.sqrt(r * r - half * half); // the distance of the chord from the centre
    const boundary = roundedPolygon(
      c,
      r,
      star.map((x) => angle.get(x) as number),
      Math.asin(half / r),
    );
    regions.set(w, { boundary, center: c });
    decorations.push({ kind: "region", boundary });
    for (const x of star) {
      const outward = Complex.fromPolar(1, angle.get(x) as number);
      const at = c.add(outward.scale(depth));
      const lateral = new Complex(-outward.im, outward.re).scale(width / 2);
      const glued = !treeEdges.has(x.edge) && !petals.has(x.edge);
      ports.set(x, {
        right: at.sub(lateral),
        left: at.add(lateral),
        outward,
        stub: glued ? r * stubLength : 0,
      });
      if (glued)
        decorations.push({
          kind: "stub",
          from: at,
          to: at.add(outward.scale(r * stubLength)),
          halfWidth: width / 2,
          label: x.name,
          color: x.color,
        });
    }
  }
  for (const [e, first] of petals) {
    // Out through the first end, counterclockwise around a point beyond the two ports, back through the second end.
    const [out, back] = [ports.get(first) as Port, ports.get(first.reversed) as Port];
    const [start, end] = [out.right.add(out.left).scale(0.5), back.right.add(back.left).scale(0.5)];
    const direction = out.outward.add(back.outward);
    const phi = direction.arg();
    const c = regions.get(e.source)?.center as Complex;
    const p = c.add(Complex.fromPolar(r * 2.2, phi));
    // Leave each port straight outwards for a bit, then go counterclockwise around p, the long way round.
    const [s1, e1] = [start.add(out.outward.scale(r * 0.5)), end.add(back.outward.scale(r * 0.5))];
    const [a0, a1] = [s1.sub(p).arg(), e1.sub(p).arg()];
    const sweep = (((a1 - a0) % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);
    const [r0, r1] = [s1.sub(p).abs(), e1.sub(p).abs()];
    const arc = Array.from({ length: 33 }, (_, i) =>
      p.add(Complex.fromPolar(r0 + ((r1 - r0) * i) / 32, a0 + (sweep * i) / 32)),
    );
    const centerline = [start, ...arc, end];
    const halfWidth = Math.min(out.left.sub(out.right).abs() / 2, r / 2);
    bands.set(e, {
      kind: "path",
      centerline: first.isForward ? centerline : centerline.toReversed(),
      halfWidth,
    });
    decorations.push({ kind: "band", centerline, halfWidth, color: e.color });
  }
  for (const e of graph.edges) {
    if (petals.has(e)) continue;
    if (!treeEdges.has(e)) {
      bands.set(e, { kind: "glue" });
      continue;
    }
    const [from, to] = [ports.get(e.forward) as Port, ports.get(e.backward) as Port];
    const centerline = [from.right.add(from.left).scale(0.5), to.right.add(to.left).scale(0.5)];
    const halfWidth = Math.min(from.left.sub(from.right).abs(), to.left.sub(to.right).abs()) / 2;
    bands.set(e, { kind: "path", centerline, halfWidth });
    decorations.push({ kind: "band", centerline, halfWidth, color: e.color });
  }
  return { geometry: "euclidean", spine, regions, ports, bands, decorations };
}

// ─── Helpers ────────────────────────────────────────────────────────────────────────────────

/**
 * The convex region bounded by the chords of the circle (c, r) centred at the given directions, each spanning the angle
 * ±halfAngle, and the arcs of the circle between them (counterclockwise).
 */
function roundedPolygon(c: Complex, r: number, directions: readonly number[], halfAngle: number): Complex[] {
  const sorted = [...directions]
    .map((d) => ((d % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI))
    .sort((a, b) => a - b);
  const points: Complex[] = [];
  sorted.forEach((d, i) => {
    const next = (sorted[(i + 1) % sorted.length] as number) + (i === sorted.length - 1 ? 2 * Math.PI : 0);
    // The chord, then the arc to the next chord.
    points.push(c.add(Complex.fromPolar(r, d - halfAngle)), c.add(Complex.fromPolar(r, d + halfAngle)));
    const [from, to] = [d + halfAngle, next - halfAngle];
    const steps = Math.max(1, Math.ceil((to - from) / 0.2));
    for (let j = 1; j < steps; j++)
      points.push(c.add(Complex.fromPolar(r, from + ((to - from) * j) / steps)));
  });
  return points;
}

function circle(c: Complex, r: number, n: number): Complex[] {
  return Array.from({ length: n }, (_, i) => c.add(Complex.fromPolar(r, (2 * Math.PI * i) / n)));
}

function centroid(points: readonly Complex[]): Complex {
  return points.reduce((s, p) => s.add(p), Complex.ZERO).scale(1 / points.length);
}

/** Scales and centres points into the disk of radius `size`. */
function normalize(points: readonly Complex[], size = 0.9): Complex[] {
  return points.map((p) =>
    normalizeLike(
      points.map((q) => [q.re, q.im] as const),
      p,
      size,
    ),
  );
}

/** Applies to `p` the normalization that {@link normalize} applies to `points`. */
function normalizeLike(points: readonly (readonly [number, number])[], p: Complex, size: number): Complex {
  const xs = points.map(([x]) => x);
  const ys = points.map(([, y]) => y);
  const c = new Complex((Math.min(...xs) + Math.max(...xs)) / 2, (Math.min(...ys) + Math.max(...ys)) / 2);
  const extent = Math.max(Math.max(...xs) - Math.min(...xs), Math.max(...ys) - Math.min(...ys), 1e-9);
  return p.sub(c).scale((2 * size) / extent);
}

function minimalDistance(points: readonly Complex[]): number {
  let best = Infinity;
  for (let i = 0; i < points.length; i++)
    for (let j = i + 1; j < points.length; j++)
      best = Math.min(best, (points[i] as Complex).sub(points[j] as Complex).abs());
  return Number.isFinite(best) ? best : 1;
}
