/**
 * Charts: how a model surface is drawn, as regions, ports and bands (port note 20).
 *
 * - Each vertex w of G₀ has a convex **region** in the chart (a polygon's interior, a disk around a base point).
 * - Each oriented edge x of G₀ has a **port** on the boundary of the region of its source: a segment through which
 *   the strands along x leave. Its lateral coordinate u runs from −1 (right) to +1 (left), looking outwards along x.
 * - Each edge of G₀ is either **glued** (the port of x is identified with the port of x̄, u ↦ −u, as for polygon sides,
 *   possibly after a straight stub sticking out of the region) or a drawn **band** (a petal around a point of the
 *   plane), along which the strands run side by side.
 *
 * Hyperbolic charts use Klein coordinates (straight lines are geodesics); the others are Euclidean.
 *
 * @module
 */
import type { Edge, OrientedEdge, Vertex } from "../graph/ribbon-graph";
import { Complex } from "../math/complex";
import type { Color } from "../math/color";
import { type DiskIsometry, regularPolygon, sidePairing } from "../geometry/hyperbolic";
import {
  spineOf,
  type PlaneModel,
  type PolygonModel,
  type Spine,
  type SpineNames,
  type SurfaceModel,
} from "../examples/models";

export interface Port {
  /** The ends of the port: lateral coordinate −1 and +1 (right and left, looking outwards). */
  readonly right: Complex;
  readonly left: Complex;
  /** The outward unit normal. */
  readonly outward: Complex;
  /** The length of a straight stub outside the region before the gluing (0 for polygon sides). */
  readonly stub: number;
}

export interface Region {
  /** A convex polygon, counterclockwise. */
  readonly boundary: readonly Complex[];
  readonly center: Complex;
}

export type Band =
  | { readonly kind: "glue" }
  /** The centreline from the port of the forward orientation to the port of the backward one, and its half width. */
  | { readonly kind: "path"; readonly centerline: readonly Complex[]; readonly halfWidth: number };

/** Things to draw that belong to the model, not to G. */
export type Decoration =
  | { readonly kind: "polygon"; readonly vertices: readonly Complex[]; readonly ideal: boolean }
  | {
      readonly kind: "side";
      readonly from: Complex;
      readonly to: Complex;
      readonly label: string;
      readonly color: Color;
    }
  | { readonly kind: "puncture"; readonly at: Complex }
  | { readonly kind: "disk"; readonly center: Complex; readonly radius: number }
  | {
      readonly kind: "band";
      readonly centerline: readonly Complex[];
      readonly halfWidth: number;
      readonly color: Color;
    }
  | {
      readonly kind: "stub";
      readonly from: Complex;
      readonly to: Complex;
      readonly halfWidth: number;
      readonly label: string;
      readonly color: Color;
    };

/** The deck transformations generated by the gluings: an isometry (hyperbolic) or a translation (flat) per port. */
export type Deck =
  | { readonly kind: "hyperbolic"; readonly generators: ReadonlyMap<OrientedEdge, DiskIsometry> }
  | { readonly kind: "translation"; readonly generators: ReadonlyMap<OrientedEdge, Complex> };

export interface Chart {
  readonly geometry: "hyperbolic" | "euclidean";
  readonly spine: Spine;
  readonly regions: ReadonlyMap<Vertex, Region>;
  readonly ports: ReadonlyMap<OrientedEdge, Port>;
  readonly bands: ReadonlyMap<Edge, Band>;
  readonly decorations: readonly Decoration[];
  /** For polygons: the generators of the deck group, one per side (the copy across that side). */
  readonly deck?: Deck;
}

/** The chart of a model. The spine is built with the given names (it must be the G₀ of the fibred surface drawn). */
export function chartOf(
  model: SurfaceModel,
  naming: SpineNames = {},
  spine: Spine = spineOf(model, naming),
): Chart {
  switch (model.kind) {
    case "polygon":
      return polygonChart(model, spine);
    case "plane":
      return planeChart(model, spine);
    case "ribbon":
      return ribbonChart(spine);
  }
}

// ─── Polygons ───────────────────────────────────────────────────────────────────────────────

/** How much of each side carries strands (the rest is near the vertices, which are cusps for ideal polygons). */
const SIDE_FRACTION = { ideal: 0.5, compact: 0.75, flat: 0.8 };

function polygonChart(model: PolygonModel, spine: Spine): Chart {
  const n = model.word.length;
  const hyperbolic = model.geometry.kind !== "flat";
  const vertices =
    model.geometry.kind === "flat"
      ? normalize(model.geometry.vertices.map(([x, y]) => new Complex(x, y)))
      : regularPolygon(n, model.geometry.kind);
  const center = hyperbolic ? Complex.ZERO : centroid(vertices);
  const [w0] = spine.graph.vertices as [Vertex];
  const sides = spine.sides as readonly OrientedEdge[];
  const fraction = SIDE_FRACTION[model.geometry.kind];
  const ports = new Map<OrientedEdge, Port>();
  const decorations: Decoration[] = [{ kind: "polygon", vertices, ideal: model.geometry.kind === "ideal" }];
  sides.forEach((x, k) => {
    const [p, q] = [vertices[k] as Complex, vertices[(k + 1) % n] as Complex];
    const mid = p.add(q).scale(0.5);
    const half = q.sub(p).scale(fraction / 2);
    const tangent = q.sub(p).scale(1 / q.sub(p).abs());
    // Counterclockwise along the side is "left" when looking outwards; the outward normal is the tangent turned right.
    ports.set(x, {
      right: mid.sub(half),
      left: mid.add(half),
      outward: new Complex(tangent.im, -tangent.re),
      stub: 0,
    });
    decorations.push({ kind: "side", from: p, to: q, label: x.name, color: x.color });
  });
  const partner = (k: number) => sides.indexOf((sides[k] as OrientedEdge).reversed);
  const deck: Deck = hyperbolic
    ? {
        kind: "hyperbolic",
        generators: new Map(sides.map((x, k) => [x.reversed, sidePairing(vertices, k, partner(k))] as const)),
      }
    : {
        kind: "translation",
        generators: new Map(
          sides.map((x, k) => {
            const mid = (i: number) =>
              (vertices[i] as Complex).add(vertices[(i + 1) % n] as Complex).scale(0.5);
            return [x.reversed, mid(partner(k)).sub(mid(k))] as const;
          }),
        ),
      };
  return {
    geometry: hyperbolic ? "hyperbolic" : "euclidean",
    spine,
    regions: new Map([[w0, { boundary: vertices, center }]]),
    ports,
    bands: new Map(spine.graph.edges.map((e) => [e, { kind: "glue" }] as const)),
    decorations,
    deck,
  };
}

// ─── The plane ──────────────────────────────────────────────────────────────────────────────

function planeChart(model: PlaneModel, spine: Spine): Chart {
  const points = normalize(
    model.points.map(([x, y]) => new Complex(x, y)),
    0.7,
  );
  const spacing = minimalDistance(points);
  const loopRadius = Math.min(0.3 * spacing, 0.25);
  const ports = new Map<OrientedEdge, Port>();
  const regions = new Map<Vertex, Region>();
  const bands = new Map<Edge, Band>();
  const decorations: Decoration[] = points.map((at) => ({ kind: "puncture", at }));
  const lassos = spine.lassos as readonly OrientedEdge[];
  const bandHalfWidth = loopRadius * 0.45;

  /** A disk region of radius r, with ports at the given angles (counterclockwise order of the star). */
  const disk = (w: Vertex, c: Complex, r: number, angles: Map<OrientedEdge, number>, portWidth: number) => {
    regions.set(w, { boundary: circle(c, r, 32), center: c });
    decorations.push({ kind: "disk", center: c, radius: r });
    for (const [x, angle] of angles) {
      const outward = Complex.fromPolar(1, angle);
      const at = c.add(outward.scale(r));
      const lateral = new Complex(-outward.im, outward.re).scale(portWidth / 2); // left of outward
      ports.set(x, { right: at.sub(lateral), left: at.add(lateral), outward, stub: 0 });
    }
  };
  /** The petal of the lasso x around the point p, leaving through port(x) and returning through port(x̄). */
  const petal = (x: OrientedEdge, p: Complex) => {
    const [out, back] = [ports.get(x) as Port, ports.get(x.reversed) as Port];
    const [start, end] = [out.right.add(out.left).scale(0.5), back.right.add(back.left).scale(0.5)];
    const towardBase = start.add(end).scale(0.5).sub(p).arg();
    const alpha = 0.35;
    const arc = Array.from({ length: 33 }, (_, i) =>
      p.add(Complex.fromPolar(loopRadius, towardBase + alpha + ((2 * Math.PI - 2 * alpha) * i) / 32)),
    );
    const centerline = [
      start,
      start.add(out.outward.scale(loopRadius * 0.3)),
      ...arc,
      end.add(back.outward.scale(loopRadius * 0.3)),
      end,
    ];
    bands.set(x.edge, {
      kind: "path",
      centerline: x.isForward ? centerline : centerline.toReversed(),
      halfWidth: bandHalfWidth,
    });
    decorations.push({ kind: "band", centerline, halfWidth: bandHalfWidth, color: x.color });
  };

  if (model.spine === "rose") {
    const [w] = spine.graph.vertices as [Vertex];
    const base = normalizeLike(model.points, new Complex(...model.basePoint), 0.7);
    const r = Math.min(0.12, 0.3 * Math.min(...points.map((p) => p.sub(base).abs())));
    const angles = new Map<OrientedEdge, number>();
    const delta = Math.min(0.25, Math.PI / (3 * points.length));
    points.forEach((p, i) => {
      const phi = p.sub(base).arg();
      const x = lassos[i] as OrientedEdge;
      angles.set(x, phi - delta);
      angles.set(x.reversed, phi + delta);
    });
    disk(w, base, r, angles, Math.min(2 * r * Math.sin(delta), 2 * bandHalfWidth));
    points.forEach((p, i) => petal(lassos[i] as OrientedEdge, p));
  } else {
    // The comb: a base point above each point, joined from left to right.
    const height = Math.min(0.35 * spacing + loopRadius, 0.5);
    const r = Math.min(0.08, 0.2 * spacing);
    const bases = points.map((p) => p.add(new Complex(0, height)));
    const vertexOf = (x: OrientedEdge) => x.source;
    points.forEach((_, i) => {
      const x = lassos[i] as OrientedEdge;
      const angles = new Map<OrientedEdge, number>([
        [x, -Math.PI / 2 - 0.35],
        [x.reversed, -Math.PI / 2 + 0.35],
      ]);
      for (const y of spine.graph.star(vertexOf(x)))
        if (y.edge !== x.edge) angles.set(y, spine.graph.star(vertexOf(x)).indexOf(y) === 0 ? Math.PI : 0);
      disk(vertexOf(x), bases[i] as Complex, r, angles, r * 0.9);
    });
    points.forEach((p, i) => petal(lassos[i] as OrientedEdge, p));
    for (const e of spine.graph.edges) {
      if (bands.has(e)) continue;
      const [from, to] = [ports.get(e.forward) as Port, ports.get(e.backward) as Port];
      const centerline = [from.right.add(from.left).scale(0.5), to.right.add(to.left).scale(0.5)];
      bands.set(e, { kind: "path", centerline, halfWidth: r * 0.45 });
      decorations.push({ kind: "band", centerline, halfWidth: r * 0.45, color: e.color });
    }
  }
  return { geometry: "euclidean", spine, regions, ports, bands, decorations };
}

// ─── Ribbon graphs ──────────────────────────────────────────────────────────────────────────

/**
 * A ribbon graph drawn as its fibred surface: a disk per vertex on a circle, a half-band (stub) per edge end, and the
 * half-bands glued pairwise at their ends (your idea: one rectangle per oriented edge, glued in the middle).
 */
function ribbonChart(spine: Spine): Chart {
  const vertices = spine.graph.vertices;
  const count = vertices.length;
  const spread = count === 1 ? 0 : 0.62;
  const r = count === 1 ? 0.32 : Math.min(0.2, (1.6 * Math.sin(Math.PI / count)) / 3);
  const stub = r * 0.9;
  const regions = new Map<Vertex, Region>();
  const ports = new Map<OrientedEdge, Port>();
  const decorations: Decoration[] = [];
  vertices.forEach((w, i) => {
    const c = Complex.fromPolar(spread, Math.PI / 2 + (2 * Math.PI * i) / count);
    regions.set(w, { boundary: circle(c, r, 32), center: c });
    decorations.push({ kind: "disk", center: c, radius: r });
    const star = spine.graph.star(w);
    const width = Math.min((2 * Math.PI * r) / star.length, r) * 0.7;
    star.forEach((x, k) => {
      const outward = Complex.fromPolar(1, Math.PI / 2 + (2 * Math.PI * k) / star.length);
      const at = c.add(outward.scale(r));
      const lateral = new Complex(-outward.im, outward.re).scale(width / 2);
      ports.set(x, { right: at.sub(lateral), left: at.add(lateral), outward, stub });
      decorations.push({
        kind: "stub",
        from: at,
        to: at.add(outward.scale(stub)),
        halfWidth: width / 2,
        label: x.name,
        color: x.color,
      });
    });
  });
  return {
    geometry: "euclidean",
    spine,
    regions,
    ports,
    bands: new Map(spine.graph.edges.map((e) => [e, { kind: "glue" }] as const)),
    decorations,
  };
}

// ─── Helpers ────────────────────────────────────────────────────────────────────────────────

function circle(c: Complex, r: number, n: number): Complex[] {
  return Array.from({ length: n }, (_, i) => c.add(Complex.fromPolar(r, (2 * Math.PI * i) / n)));
}

function centroid(points: readonly Complex[]): Complex {
  return points.reduce((s, p) => s.add(p), Complex.ZERO).scale(1 / points.length);
}

/** Scales and centres points into the disk of radius `size`. */
function normalize(points: readonly Complex[], size = 0.9): Complex[] {
  return points.map((p) =>
    normalizeLike(
      points.map((q) => [q.re, q.im] as const),
      p,
      size,
    ),
  );
}

/** Applies to `p` the normalization that {@link normalize} applies to `points`. */
function normalizeLike(points: readonly (readonly [number, number])[], p: Complex, size: number): Complex {
  const xs = points.map(([x]) => x);
  const ys = points.map(([, y]) => y);
  const c = new Complex((Math.min(...xs) + Math.max(...xs)) / 2, (Math.min(...ys) + Math.max(...ys)) / 2);
  const extent = Math.max(Math.max(...xs) - Math.min(...xs), Math.max(...ys) - Math.min(...ys), 1e-9);
  return p.sub(c).scale((2 * size) / extent);
}

function minimalDistance(points: readonly Complex[]): number {
  let best = Infinity;
  for (let i = 0; i < points.length; i++)
    for (let j = i + 1; j < points.length; j++)
      best = Math.min(best, (points[i] as Complex).sub(points[j] as Complex).abs());
  return Number.isFinite(best) ? best : 1;
}
